name: Unit tests

on: [push, pull_request]

jobs:
  tests:
    name: All tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Passerby
        uses: actions/checkout@v3
      - name: Install libsodium.js
        run: git clone https://github.com/jedisct1/libsodium.js
      - name: Copy passerby.json
        run: cp $GITHUB_WORKSPACE/.github/workflows/passerby.json $GITHUB_WORKSPACE
      - name: Run tests
        run: $GITHUB_WORKSPACE/.github/workflows/test.sh
        env:
          NODE_PATH=${{ github.workspace }}/libsodium.js/dist/modules/

